version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/officegen-api"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "HlexNC"
    open-pull-requests-limit: 10
    groups:
      npm-officegen:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/python-api"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "HlexNC"
    open-pull-requests-limit: 10
    groups:
      pip-python-api:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/document-conversion"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "HlexNC"
    open-pull-requests-limit: 10
    groups:
      npm-document-conversion:
        patterns:
          - "*"
