version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/officegen-api"
    schedule:
      interval: "daily"
    reviewers:
      - "HlexNC"

  - package-ecosystem: "pip"
    directory: "/python-api"
    schedule:
      interval: "daily"
    reviewers:
      - "HlexNC"

# Interval can be 'live', 'daily', 'weekly', or 'monthly'


  - package-ecosystem: "npm"
    directory: "/privateomega-lib"
    schedule:
      interval: "daily"
    reviewers:
      - "HlexNC"

# Interval can be 'live', 'daily', 'weekly', or 'monthly'
