version: 2
updates:  
  - package-ecosystem: "npm"
    directory: "/document-conversion"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

# Interval can be 'live', 'daily', 'weekly', or 'monthly'
