version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/officegen-api"
    schedule:
      interval: "daily"
      # day: "saturday"
    reviewers:
      - "HlexNC"
    # open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/python-api"
    schedule:
      interval: "daily"
      # day: "saturday"
    reviewers:
      - "HlexNC"
    # open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/document-conversion"
    schedule:
      interval: "daily"
      # day: "saturday"
    reviewers:
      - "HlexNC"
    # open-pull-requests-limit: 10
