name: 'Dependabot Batcher: Scheduled'
on:
  schedule:
    - cron: '0 9 * * 5'

jobs:
  dependabot-batcher:
    name: 'Combine Dependabot PRs'
    uses: Legal-and-General/dependabot-batcher
    token: ${{ secrets.BATCHER_TOKEN }