name: 'Dependabot Batcher: Scheduled'
on:
  schedule:
    - cron: '0 9 * * 5'

jobs:
  dependabot-batcher:
    name: 'Combine Dependabot PRs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BATCHER_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Dependabot Batcher'
        uses: Legal-and-General/dependabot-batcher@v1.0.3
        with:
          token: ${{ secrets.BATCHER_TOKEN }}
  
