name: Publish NPM Package

on:
  push:
    branches:
      - main
      - feature/npm-package

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org/'
      - run: cd officegen-api/ && npm ci
      - run: cd officegen-api/ && npm publish --access private
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
