name: Publish NPM Package

on:
  push:
    branches:
      - main
      - feature/npm-package
permissions:
  contents: write
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hlexnc'

      - name: Install dependencies
        run: npm install
        working-directory: officegen-api/

      - name: Publish package
        id: publish
        run: npm publish
        working-directory: officegen-api/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check for publish error
        if: steps.publish.outcome == 'failure'
        run: echo "Publish failed due to existing version"

      - name: Increment package version
        if: steps.publish.outcome == 'failure'
        run: |
          npm version patch
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push
        working-directory: officegen-api/

      - name: Publish package again
        if: steps.publish.outcome == 'failure'
        run: npm publish
        working-directory: officegen-api/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
