name: Publish Document Conversion NPM Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@universityofnicosia'
      - run: npm install
        working-directory: privateomega-lib/
      - run: npm publish
        working-directory: privateomega-lib/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}