name: Publish NPM Package

on:
  push:
    branches:
      - main
      - feature/npm-package

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@universityofnicosia'
      - run: npm ci
        working-directory: officegen-api/
      - run: npm publish
        working-directory: officegen-api/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}